name: kashmir_vegitable
description: Kashmir Vegitable - Delhi vegetable delivery app
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  url_launcher: ^6.3.2

flutter:
  uses-material-design: true
